config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :providers do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :provider
end

app/models/provider.rb
class Provider < ActiveRecord::Base

  has_many :comments

  geocoded_by :address
  after_validation :geocode

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.provider_id = params[:provider_id]
    @comment.save
    redirect_to provider_path(@comment.provider)
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
    @hash = Gmaps4rails.build_markers(@providers) do |provider, marker|
      marker.lat provider.latitude
      marker.lng provider.longitude
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @comment = Comment.new
    @comment.provider_id = @provider.id

  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :address, :description, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @provider, @comment ] do |f| %>
  <p>
    <%= f.label :author_name %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Add Comment' %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Aidin App', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <%= render 'layouts/navigation_links' %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aidin App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Aidin App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<!-- ********** SIDE IMAGE - SECTION ********** -->
  <section id="about"></section>
  <section class="side-image text-heavy clearfix">
    <div class="image-container col-md-5 col-sm-3 pull-left">
      <div class="background-image-holder">
        <%= image_tag("aboutaidin.png") %>
      </div><!--/background-img-holder-->
    </div><!--/img-container-->

    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-6 col-sm-8 col-sm-offset-4 content clearfix">
          <h1>About Aidin and This App</h1>

          <p class="lead">Aidin empowers hospital leaders, patients, and post acute providers with real-time quality and satisfaction data to make informed decisions.</p>

          <p class="lead">This app allows users to log in and log out. Visitors can view empowering information about post-acute providers and leave comments about said providers by clicking "View Providers" on the home page. The providers can be added, updated, or deleted ("able to create, edit, delete records").</p>

          <p class="lead">There will be a list of providers whose locations are shown on a Google map ("geocoder API use"). If a visitor clicks on "show," he or she will see information about that provider. A provider has many comments ("include relational objects"). A visitor may click on the "Comments" link to toggle comments about the provider ("AJAX request").</p>

          <p class="lead">If a visitor adds a new provider with an address (e.g., Paris, France or Baltimore, USA), the provider's location will show up on a Google map below the list of all providers.</p>

          <p class="lead">Finally, the navigation bar and comments use partials ("uses partials").</p>

          <%= link_to 'Go Back', root_path, :class=>"btn btn-conf btn-green" %> <br>
          <div class="col-sm-6 no-pad-left feature">
            <h5>Process</h5>
            <p>Aidin’s reimagined referral process benefits both hospitals and post acute care providers. Increase the visibility of referrals for post-acute care providers.</p>
          </div>
          <div class="col-sm-6 no-pad-left feature">
            <h5>Strategy</h5>
            <p>Maximize your risk based reimbursement by engaging the right post acute care provider for your patient population.</p>
          </div>
        </div><!--col-md-6 col-sm-8 -->

      </div><!-- /row -->
    </div><!--/container -->
  </section><!--Side Image Section -->

app/views/providers/_comment.html.erb
<div>
  <h4>Comment by: <%= comment.author_name %></h4>
  <p><%= comment.body %></p>
</div>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<!-- add google scripts into my dom -->
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<p id="notice"><%= notice %></p>

<h1>Listing Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="20"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.address %></td>
        <td><%= provider.description %></td>
        <td><%= provider.latitude %></td>
        <td><%= provider.longitude %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

<!-- added div to bear google map for providers -->
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @provider.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @provider.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @provider.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @provider.longitude %>
</p>

<p><h3><%= link_to "Show Comments", "#", id: "comments-link" %></h3>
</p>

<section id="comments-section">

<section id="comments">
<%= render partial: 'providers/comment', collection: @provider.comments %>
</section>

<%= render partial: 'comments/form' %>
</section>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- ********** HEADER ********** -->
  <section id="home"></section>
  <div id="h">
      <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>Find and rate the best post-acute care providers in your area.</h1>
            <%= link_to('About This App', page_path('about'), class: "btn btn-conf btn-green") %>
            <%= link_to('View Providers', providers_path, class: "btn btn-conf btn-green") %>
        </div>
      </div>
      </div><!-- /.container -->
  </div><!--/H -->